"""add timestamps to all tables

Revision ID: 280de2a7eb34
Revises: 9fcd61b1d574
Create Date: 2025-07-11 13:11:39.569564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280de2a7eb34'
down_revision: Union[str, None] = '9fcd61b1d574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Foods tablosu
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
    
    # Recipes tablosu
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
    
    # Roles tablosu
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), 
                                     nullable=False, 
                                     server_default=sa.text('CURRENT_TIMESTAMP')))
    
    # Users role_id'yi nullable=False yap
   # op.alter_column('users', 'role_id',
   #            existing_type=sa.INTEGER(),
    #           nullable=False)
    
    # ### end Alembic commands ###
