"""add allergen system tables

Revision ID: 4e6f581e135b
Revises: f0a62a2fdf38
Create Date: 2025-07-11 08:44:02.703627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4e6f581e135b'
down_revision: Union[str, None] = 'f0a62a2fdf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergens_code'), 'allergens', ['code'], unique=True)
    op.create_index(op.f('ix_allergens_id'), 'allergens', ['id'], unique=False)
    op.create_table('allergen_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allergen_id', 'language_code')
    )
    op.create_index(op.f('ix_allergen_translations_id'), 'allergen_translations', ['id'], unique=False)
    op.create_index(op.f('ix_allergen_translations_language_code'), 'allergen_translations', ['language_code'], unique=False)
    op.create_table('food_allergens',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('food_id', 'allergen_id')
    )
    op.create_table('recipe_allergens',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'allergen_id')
    )



def downgrade() -> None:
    op.drop_table('recipe_allergens')
    op.drop_table('food_allergens')
    op.drop_index(op.f('ix_allergen_translations_language_code'), table_name='allergen_translations')
    op.drop_index(op.f('ix_allergen_translations_id'), table_name='allergen_translations')
    op.drop_table('allergen_translations')
    op.drop_index(op.f('ix_allergens_id'), table_name='allergens')
    op.drop_index(op.f('ix_allergens_code'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
