"""firma adı eklendi

Revision ID: 6ceab54ca39f
Revises: 2177002e0445
Create Date: 2025-07-07 15:36:54.287418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ceab54ca39f'
down_revision: Union[str, None] = '2177002e0445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firmName', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_firmName'), 'users', ['firmName'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firmName'), table_name='users')
    op.drop_column('users', 'firmName')
    # ### end Alembic commands ###
