"""Remove allergen_translations table

Revision ID: 9c959c40ede0
Revises: 801b1bf74725
Create Date: 2025-07-13 16:14:55.302056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c959c40ede0'
down_revision: Union[str, None] = '801b1bf74725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_allergen_translations_id', table_name='allergen_translations')
    op.drop_index('ix_allergen_translations_language_code', table_name='allergen_translations')
    op.drop_table('allergen_translations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('allergen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name='allergen_translations_allergen_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='allergen_translations_pkey'),
    sa.UniqueConstraint('allergen_id', 'language_code', name='allergen_translations_allergen_id_language_code_key')
    )
    op.create_index('ix_allergen_translations_language_code', 'allergen_translations', ['language_code'], unique=False)
    op.create_index('ix_allergen_translations_id', 'allergen_translations', ['id'], unique=False)
    # ### end Alembic commands ###
