"""remove firmname column

Revision ID: bb91eaf09a08
Revises: 6ceab54ca39f
Create Date: 2025-07-07 15:13:49.980628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb91eaf09a08'
down_revision: Union[str, None] = '6ceab54ca39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firmName'), table_name='users')
    op.drop_column('users', 'firmName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firmName', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_firmName'), 'users', ['firmName'], unique=1)
    # ### end Alembic commands ###
