"""remove username column

Revision ID: bf830c7258bf
Revises: bb91eaf09a08
Create Date: 2025-07-09 10:31:17.582713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf830c7258bf'
down_revision: Union[str, None] = 'bb91eaf09a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    # ### end Alembic commands ###
