"""Add all translation tables and allergen timestamps

Revision ID: c112c56e8da9
Revises: 2053ac649a9b
Create Date: 2025-07-14 10:19:59.070360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c112c56e8da9'
down_revision: Union[str, None] = '2053ac649a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allergen_id', 'language_id')
    )
    op.create_index(op.f('ix_allergen_translations_id'), 'allergen_translations', ['id'], unique=False)
    op.create_table('role_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'language_id')
    )
    op.create_index(op.f('ix_role_translations_id'), 'role_translations', ['id'], unique=False)
    op.create_table('recipe_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'language_id')
    )
    op.create_index(op.f('ix_recipe_translations_id'), 'recipe_translations', ['id'], unique=False)
    op.add_column('allergens', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('allergens', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allergens', 'updated_at')
    op.drop_column('allergens', 'created_at')
    op.drop_index(op.f('ix_recipe_translations_id'), table_name='recipe_translations')
    op.drop_table('recipe_translations')
    op.drop_index(op.f('ix_role_translations_id'), table_name='role_translations')
    op.drop_table('role_translations')
    op.drop_index(op.f('ix_allergen_translations_id'), table_name='allergen_translations')
    op.drop_table('allergen_translations')
    # ### end Alembic commands ###
